name: brain_builder
dependencies:
- certifi=2016.2.28=py36_0
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- readline=6.2=2
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xarray=0.9.6=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - chardet==3.0.4
  - coverage==4.4.1
  - docutils==0.14
  - idna==2.6
  - lockfile==0.12.2
  - luigi==2.7.0
  - py==1.4.34
  - pytest==3.2.2
  - pytest-cov==2.5.1
  - python-daemon==2.1.2
  - requests==2.18.4
  - tornado==4.5.2
  - urllib3==1.22
